# 文件说明：拾光记微服务后端认证中心配置文件，统一维护服务端口、注册发现、数据源和中间件参数。
spring:
  application:
    name: auth-center
  datasource:
    url: jdbc:mysql://localhost:3306/cot_identity?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    #password: 0924
    password: Liu0924#
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 10
      maximum-pool-size: 50
      idle-timeout: 30000
      connection-timeout: 3000

# MyBatis-Plus 配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true


jwt:
  secret: mySecretKeyForJWTGenerationWithEnoughLength12345678
  expiration: 3600000       # 1小时
  refreshExpiration: 604800000  # 7天

logging:
  level:
    org.example.authcenter: DEBUG
